default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: eCommerceApp
  username: postgres
  password: kunmasin
  host: localhost

test:
  <<: *default
  database: test_eCommerceApp
  username: postgres
  password: kunmasin
  host: localhost

production:
  <<: *default
  database: eCommerceApp_production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  url: <%= ENV["DATABASE_URL"] %>
