default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: eCommerceApp
  username: postgres
  password: kunmasin
  host: localhost

test:
  <<: *default
  database: test_eCommerceApp
  username: postgres
  password: kunmasin
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
